heat_template_version: rocky

parameters:
  ssh_keys:
    type: comma_delimited_list

resources:

  logs_port:
    type: OS::Neutron::Port
    properties:
      network_id: private_net
      security_groups:
        - internal_security_group
      fixed_ips:
        - subnet_id: private_subnet
          ip_address: 192.168.10.61

  logs:
    type: vm-template.yaml
    properties:
      name: elastic
      flavor: s20.xlarge
      network_port: {get_resource: logs_port}
      ssh_keys: {get_param: ssh_keys}
