apiVersion: v1
kind: Service
metadata:
  name: tags-service
spec:
  selector:
    app: tags-service
  ports:
  - protocol: TCP
    port: 50051

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tags-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tags-service
  template:
    metadata:
      labels:
        app: tags-service
    spec:
      containers:
      - name: tags-service
        image: gitlab-devops.cloud.rennes.enst-bretagne.fr:4567/devops/shared/tags:latest
        env:
        - name: DATABASE_NAME
          value: "user-tags-db"
        - name: AUTH_DATABASE_NAME
          value: "user-tags-db"
        - name: MONGO_HOST
          value: "mongo.cloud.rennes.enst-bretagne.fr"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: password
        ports:
        - containerPort: 50051
      imagePullSecrets:
      - name: regcred
