heat_template_version: rocky

parameters:
  ssh_keys:
    type: comma_delimited_list

resources:

  metrics_port:
    type: OS::Neutron::Port
    properties:
      network_id: private_net
      security_groups:
        - internal_security_group
      fixed_ips:
        - subnet_id: private_subnet
          ip_address: 192.168.10.51

  metrics:
    type: vm-template.yaml
    properties:
      name: prometheus
      flavor: s10.large
      network_port: {get_resource: metrics_port}
      ssh_keys: {get_param: ssh_keys}
