heat_template_version: rocky

description: Photo Sharing Application Heat Stack

parameters:
  ssh_keys:
    type: comma_delimited_list

resources:

  # ==================================================
  # SECURITY GROUPS
  # ==================================================
  external_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: "External available connections"
      name: external_security_group
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 6443
          port_range_max: 6443
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 8080
          port_range_max: 8080
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 3000
          port_range_max: 3000
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 9090
          port_range_max: 9090
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 5601
          port_range_max: 5601

  internal_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: "Open all the ports inside the private network"
      name: internal_security_group
      rules:
        - remote_ip_prefix: 192.168.10.0/24
          direction: ingress

  # ==================================================
  # NETWORK
  # ==================================================
  private_net:
    type: OS::Neutron::Net
    properties:
      name: "private_net"

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: "192.168.10.0/24"
      dns_nameservers: [ "192.44.75.10" ]
      ip_version: 4
      allocation_pools:
        - start: "192.168.10.200"
          end: "192.168.10.254"
      name: "private_subnet"

  gateway_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: external
      name: "gateway_router"

  gateway_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: gateway_router}
      subnet_id: { get_resource: private_subnet}

  # ==================================================
  # BASTION
  # ==================================================
  bastion_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net}
      security_groups: [ get_resource: external_security_group,  get_resource: internal_security_group]
      fixed_ips:
        - subnet_id: { get_resource: private_subnet}
          ip_address: 192.168.10.11

  bastion_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: external
      port_id: { get_resource: bastion_port }

  bastion:
    type: template-common.yaml
    properties:
      name: bastion
      flavor: s10.medium
      network_port: { get_resource: bastion_port}
      ssh_keys: {get_param: ssh_keys}
