heat_template_version: rocky

parameters:
  flavor:
    type: string
  security_group:
    type: string
  network_id:
    type: string
  subnet_id:
    type: string


resources:

  controller_port:
    type: OS::Neutron::Port
    properties:
      network_id: {get_param: network_id}
      security_groups: 
        - get_param: security_group
      fixed_ips:
        - subnet_id: {get_param: subnet_id}
          ip_address: 192.168.10.31

  controller:
    type: OS::Nova::Server
    properties:
      name: k8s-cont
      image: ubuntu-20.04
      flavor: {get_param: flavor}
      networks:
        - port: {get_resource: controller_port}

  worker1_port:
    type: OS::Neutron::Port
    properties:
      network_id: {get_param: network_id}
      security_groups: 
        - get_param: security_group
      fixed_ips:
        - subnet_id: {get_param: subnet_id}
          ip_address: 192.168.10.41

  worker1:
    type: OS::Nova::Server
    properties:
      name: k8s-worker-1
      image: ubuntu-20.04
      flavor: {get_param: flavor}
      networks:
        - port: {get_resource: worker1_port}

  worker2_port:
    type: OS::Neutron::Port
    properties:
      network_id: {get_param: network_id}
      security_groups: 
        - get_param: security_group
      fixed_ips:
        - subnet_id: {get_param: subnet_id}
          ip_address: 192.168.10.42

  worker2:
    type: OS::Nova::Server
    properties:
      name: k8s-worker-2
      image: ubuntu-20.04
      flavor: {get_param: flavor}
      networks:
        - port: {get_resource: worker2_port}

  worker3_port:
    type: OS::Neutron::Port
    properties:
      network_id: {get_param: network_id}
      security_groups: 
        - get_param: security_group
      fixed_ips:
        - subnet_id: {get_param: subnet_id}
          ip_address: 192.168.10.43

  worker3:
    type: OS::Nova::Server
    properties:
      name: k8s-worker-3
      image: ubuntu-20.04
      flavor: {get_param: flavor}
      networks:
        - port: {get_resource: worker3_port}
