apiVersion: v1
kind: Service
metadata:
  name: photo-service
spec:
  selector:
    app: photo-service
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photo-service
  template:
    metadata:
      labels:
        app: photo-service
    spec:
      containers:
      - name: photo-service
        image: gitlab-devops.cloud.rennes.enst-bretagne.fr:4567/a21cespe/devops-s22_03/photo:latest
        env:
        - name: DATABASE_NAME
          value: "user-photo-db"
        - name: AUTH_DATABASE_NAME
          value: "user-photo-db"
        - name: MONGO_HOST
          value: "mongo.cloud.rennes.enst-bretagne.fr"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: password
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
